### ISSUE TITLE
Can we send custom stickers created in Line creator studio?

### ISSUE THREAD

**Issue by shinmm** [shinmm/line-bot-freshers#13]
Relevant links 
* https://creator.line.me/en/studio/
* https://developers.line.biz/en/docs/messaging-api/sticker-list/

**Comment by pvenkat998** [comment]
test: custom stickers purchased and free stickers obtained by 'add friend action'
couldn't send the sticker. 
error message attached
![image](https://user-images.githubusercontent.com/37797776/115812511-77c75300-a42c-11eb-9dbf-90f972d3799f.png)

**Comment by pvenkat998** [comment]
make custom stickers and applied for verification and approval

**Comment by shinmm** [comment]
yea, it seems like you can only send specific stickers(official ones) via the Messaging API 
I think we could maybe send a link to the sticker set or something but sending the stickers directly seems to be a no go

**Comment by pvenkat998** [comment]
I believe we can close this issue as 'not possible', you were right, the ones in the list are the **"only usable ones"** 
https://developers.line.biz/ja/docs/messaging-api/sticker-list/

p.s.: I believe they do it so, people dont use it these accounts as a marketing technique to sell their stickers! lol
